// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOEyUwmTgPc3MJwuOQft0ywjCr2aMWlDA',
    appId: '1:926481717016:android:aa5e3892da1f895f65706d',
    messagingSenderId: '926481717016',
    projectId: 'daralbanat-8d972',
    storageBucket: 'daralbanat-8d972.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOEyUwmTgPc3MJwuOQft0ywjCr2aMWlDA',
    appId: '1:926481717016:ios:aa5e3892da1f895f65706d',
    messagingSenderId: '926481717016',
    projectId: 'daralbanat-8d972',
    storageBucket: 'daralbanat-8d972.appspot.com',
    iosClientId: '',
    iosBundleId: 'com.example.daralbanatWebview',
  );
}
